// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.citzag.daos;

import com.citzag.daos.CzUsers;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CzUsers_Roo_Configurable {
    
    declare @type: CzUsers: @Configurable;
    
}
